#ifndef __RT_AI_NETWORK_MODEL_H
#define __RT_AI_NETWORK_MODEL_H

#include <network.h>
#include <network_data.h>

/* model info ... */

// model name
#define RT_AI_NETWORK_MODEL_NAME			"network"
#define RT_AI_NETWORK_WORK_BUFFER_BYTES		AI_NETWORK_DATA_ACTIVATIONS_SIZE
#define RT_AI_NETWORK_DATA_WEIGHTS_SIZE		AI_NETWORK_DATA_WEIGHTS_SIZE

#define RT_AI_NETWORK_BUFFER_ALIGNMENT		AI_NETWORK_ACTIVATIONS_ALIGNMENT

#define RT_AI_NETWORK_IN_NUM				AI_NETWORK_IN_NUM
#define RT_AI_NETWORK_IN_1_SIZE				AI_NETWORK_IN_1_SIZE
#define RT_AI_NETWORK_IN_1_SIZE_BYTES		AI_NETWORK_IN_1_SIZE_BYTES
#define RT_AI_NETWORK_IN_TOTAL_SIZE_BYTES	NULL
#define RT_AI_NETWORK_IN_SIZE_BYTES			NULL


#define RT_AI_NETWORK_OUT_NUM				AI_NETWORK_OUT_NUM
#define RT_AI_NETWORK_OUT_1_SIZE			AI_NETWORK_OUT_1_SIZE
#define RT_AI_NETWORK_OUT_1_SIZE_BYTES		AI_NETWORK_OUT_1_SIZE_BYTES
#define RT_AI_NETWORK_OUT_TOTAL_SIZE_BYTES	NULL
#define RT_AI_NETWORK_OUT_SIZE_BYTES		NULL


#define RT_AI_NETWORK_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
